### ISSUE TITLE
Implement Transform Tool

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#1253]
Possibility to move/scale/rotate elements.

In the UI, this might be a subset of the Select Tool, but we track it as a separate GitHub issues since it may in the future be a separate tool, and the backend for transforming elements is quite unrelated to the backend for selecting elements.

**Comment by dalboris** [comment]
Already implemented: drag move with linear transform of incident edges: #1284

**Comment by PixelRick** [comment]
Duplicate of #1362.
