### ISSUE TITLE
HLSL errors when compiling on Windows

### ISSUE THREAD

**Issue by Arcnor** [vgc/vgc#1303]
Hi,

I've been trying to build the project on Windows 10, but it looks like HLSL shaders fail to compile:

```
vgc\libs\vgc\graphics\shaders\d3d11\screen_space_displacement.v.hlsl(11,17-23): error X4502: invalid vs_2_0 input semantic 'DISP0' [vgc\build\libs\vgc\graphics\vgc_graphics_resources.vcxproj]
```

My DX knowledge is spotty, but `DISP0` doesn't seem like a valid semantic anyway? Same for `ROT0` or `OFFSET0`. Should this compile, and if it should, any idea of how to fix those errors?

Thanks in advance!

**Comment by PixelRick** [comment]
Hi. To my knowledge we can use any semantic name that we like. I will check tomorrow at work and will be back with an answer.

**Comment by PixelRick** [comment]
I am not sure why you are ending up compiling shaders during project compilation since the shaders are supposed to be resources. VGC uses Direct3D11 and compiles shaders targeting Shader Model 4.0 at the moment and probably 5.0 later on.

But if you wanted to manually compile them, you should target at least 4.0 and you will be good to go.

FYI about user-defined semantics, the HLSL documentation states:

> In general, data passed between pipeline stages is completely generic and is not uniquely interpreted by the system; arbitrary semantics are allowed which have no special meaning.
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics

But it seems they have only been introduced with Direct3D10 (Shader Model 4.0), to be used in layout descriptors.
Also, Direct3D9's semantics without side-effects are processed as user-defined semantics in Direct3D10+, and the others have been remapped to SV_x semantics.

**Comment by Arcnor** [comment]
I just wanted to test the project, I'm not sure why it's compiling shaders either, but I don't know what parts are needed and which ones are not :). I'm just running `cmake --build build` and created the project normally, just with the vcpkg toolchain line.

If it helps, these are the last lines before the errors:

```
  vgc_core_lib.vcxproj -> vgc\build\Debug\bin\vgccore.dll
  vgc_core_wraps.vcxproj -> vgc\build\Debug\python\vgc\core.cp39-win_amd64.pyd
  vgc_style_lib.vcxproj -> vgc\build\Debug\bin\vgcstyle.dll
  libtess2.vcxproj -> vgc\build\third\libtess2\Debug\libtess2.lib
  vgc_geometry_lib.vcxproj -> vgc\build\Debug\bin\vgcgeometry.dll
  vgc_style_wraps.vcxproj -> vgc\build\Debug\python\vgc\style.cp39-win_amd64.pyd
  vgc_geometry_wraps.vcxproj -> vgc\build\Debug\python\vgc\geometry.cp39-win_amd64.pyd
  vgc_vacomplex_lib.vcxproj -> vgc\build\Debug\bin\vgcvacomplex.dll
  vgc_dom_lib.vcxproj -> vgc\build\Debug\bin\vgcdom.dll
  Updated shaders/d3d11/screen_space_displacement.v.hlsl
  Updated shaders/d3d11/simple.f.hlsl
```

**Comment by dalboris** [comment]
@Arcnor It looks like you are compiling using MSBuild (cf *.vcxproj files). Currently, we are only supporting Ninja, which should be the default when opening your project as a CMake project in VS 2019+.

Open Visual Studio > Open > **Folder** > vgc (root of the git repository) 

Your CMake settings (Project > CMake Settings) should look something like:

![image](https://github.com/vgc/vgc/assets/4809739/9ded95da-18d0-4dc6-992b-8897a3b15b4b)

Important settings are telling it where to find Qt, for example :

`-DQt5_DIR="C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5”`

And possibly where to find vcpkg, if you didn't do “vcpkg integrate install”:

`C:/Users/dalbo/vcpkg/scripts/buildsystems/vcpkg.cmake`

**Comment by Arcnor** [comment]
Thanks, I haven't used Ninja because I'm using the command line (and Ninja doesn't work here on my system for some reason), but I'll try with that instead and report back.

Regarding QT5, I've just added that to VCPKG and used manifest mode instead, which simplifies installation quite a bit (just bootstrap vcpkg, CMake configure, then build).

**Comment by Arcnor** [comment]
Ninja + MSVC2022 works fine and now I can run the project, thanks for your help.

At some point I recommend you look into fixing Clang for Windows, in my tests (for gamedev) I've gotten a nice speedup without doing anything but recompiling, but of course this depends on a lot of things.

**Comment by dalboris** [comment]
For now, the only supported combination on Windows is Ninja + MSVC. Although once upon a time we were using MSBuild, but this was before we added shaders.

In case you want to try MSBuild, perhaps you may try manually editing the generated file `vgc\build\libs\vgc\graphics\vgc_graphics_resources.vcxproj` to exclude the shaders from the build. This might help:

https://stackoverflow.com/questions/219381/how-to-exclude-files-from-visual-studio-compile

But ideally, it should be the responsibility of our CMake files to generate a more appropriate `vgc_graphics_resources.vcxproj` that does not try to compile the shaders.
