### ISSUE TITLE
Error running on NixOS

### ISSUE THREAD

**Issue by zeronobody0** [vgc/vgc#1823]
I got the project to build on NixOS using [my own derivation](https://codeberg.org/shitpostalotl/bespoke/src/branch/main/pkgs/vgc.nix) (apologies for the CMakeLists mutilation). However, when I try to run it, I get the following error:

```
terminate called after throwing an instance of 'vgc::core::FileError'
  what():  Cannot open file /build/source/build/Release/resources/ui/stylesheets/default.vgcss.
```

Please help!

**Comment by dalboris** [comment]
Hi @zeronobody0 ,

VGC requires resource files at runtime, including the stylesheet mentioned in the error above, but also shaders, fonts, and cursors. Normally, the provided CMakeLists make sure that:

- All these resource files are copied in some appropriate location
- A `vgc.conf` file is created next to the `vgcillustration` binary which tells VGC at runtime where are the resources

For example, here is a typical folder structure that I get after compiling in Debug mode in Ubuntu within Qt Creator:

![image](https://github.com/user-attachments/assets/3a4afc45-0fa2-423d-8db8-90b6ca9aec6d)

And here is the content of `vgc.conf`:

```
BasePath = /home/boris/vgc/build/Desktop_Qt_5_15_2_GCC_64bit-Debug/Debug
PythonHome = /usr
```

I'm not familiar with Nix, but you should ensure that after compilation/installation you have a similar structure and `vgc.conf` file next to the application binary. Currently, you may have mutilated the CMakeLists too much for this to happen.

A first step for you might be to manually copy all the resources files from the source to where VGC currently looks for them.

That is copy all these folders:

```
<vgc-git-root>/apps/illustration/icons/
<vgc-git-root>/libs/vgc/graphics/fonts/
<vgc-git-root>/libs/vgc/graphics/shaders/
<vgc-git-root>/libs/vgc/ui/icons/
<vgc-git-root>/libs/vgc/ui/stylesheets/
<vgc-git-root>/libs/vgc/tools/cursors/
<vgc-git-root>/libs/vgc/tools/icons/
```

to:

```
/build/source/build/Release/resources/illustration/icons/
/build/source/build/Release/resources/graphics/fonts/
/build/source/build/Release/resources/graphics/shaders/
/build/source/build/Release/resources/ui/icons/
/build/source/build/Release/resources/ui/stylesheets/
/build/source/build/Release/resources/tools/cursors/
/build/source/build/Release/resources/tools/icons/
```

The next would be to ensure that this is done automatically, which is normally the case when doing the typical `cmake && make`. This is implemented in the `vgc_add_app` and `vgc_add_library` functions in `tools/VgcTools.cmake` and in `tools/copy_resources.py`.

**Comment by zeronobody0** [comment]
`vgc.conf` has the wrong `BasePath`, probably from reading the global path from inside the build sandbox. Nix might have a system to find the correct directory, but using relative path would be a good idea to begin with.
