### ISSUE TITLE
Use std::string::operator+= instead of std::string::append

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#29]
I somehow just realized today that the following was illegal (see [here](https://stackoverflow.com/questions/1472048/how-to-append-a-char-to-a-stdstring)):

```
char c = 'd';
std::string s = "Hello worl";
s.append(c); // Compiler error: no matching member function for call to 'append'
```

We should use the following instead:

```
char c = 'd';
std::string s = "Hello worl";
s += c; 
```

For consistency, we should prefer using `+=` instead of `append` for appending a `std::string` as well:

```
std::string c = "d";
std::string s = "Hello worl";
s += c; // s.append(c) is also legal, but prefer += for consistency with appending a char
```

**Comment by ThePreviousOne** [comment]
@dalboris so why not make a PR?

**Comment by dalboris** [comment]
We should now prefer the new write and format methods. Closing this as the transition will happen by itself as part of other code change.

**Comment by dalboris** [comment]
See: #301
