### ISSUE TITLE
Upgrade to Qt 5.12

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#33]
So far, I was using Qt 5.6 as per previous recommendation of the [VFX Reference Platform](http://www.vfxplatform.com/), due to PySide2 not yet ported for newer versions of Qt. But the recommendation for 2019 is now to use 5.12, so I'd better upgrade to this version.

**Comment by dalboris** [comment]
Note: switching to Qt 5.12 has the advantage that binaries for MSVC 2017 are provided, and I'm having issues with MSVC 2015 (see #32) which might not be present in MSVC 2017.

**Comment by dalboris** [comment]
It seems that I can postpone this since:
- Qt 5.11.1 + MSVC 2017 doesn't seem to solve #32 which occured with Qt 5.6.3 + MSVC 2015
- Qt 5.12 is only released at the end of November 2018 anyway (see [release plan](https://wiki.qt.io/Qt_5.12_Release)).

**Comment by Robot-Fromage** [comment]
I think it is a good idea, Qt5.11+ is already very stable on Windows, and you will benefit from cool features of  Qt WebEngine if you plan on using it.

**Comment by dalboris** [comment]
Yes, at this point I'm already using Qt 5.11.2  or even Qt 5.12-rc for all my local builds. I'lll update the README file once Qt 5.12 is officially released.

**Comment by dalboris** [comment]
Qt 5.12 LTS just released yesterday: http://blog.qt.io/blog/2018/12/06/qt-5-12-lts-released/
