### ISSUE TITLE
Make compile lacks opengl library

### ISSUE THREAD

**Issue by allphfa** [vgc/vgc#34]
sudo apt-get install libgl1-mesa-dev

**Comment by dalboris** [comment]
Thanks for the feedback! I'll probably add this to the README file. Which flavor of Linux where you using? I believe on Ubuntu 18.04 this wasn't necessary (i.e., this dependency was already installed by default), but I may be wrong.

**Comment by dalboris** [comment]
More investigation: on my current Kubuntu 18.04 system, I don't have libgl1-mesa-dev installed and VGC compiles fine. However it seems possible that the reason I didn't need it is that I have a proprietary NVIDIA driver installed. I updated the README file accordingly.
