### ISSUE TITLE
Define VGC integer types

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#39]
The rationale for having "flexible" integer types in C++ (for example, `int` is "at least 16bit") mostly doesn't apply to VGC. Indeed, the rationale for these types is that the compiler may choose the most appropriate native type, but most if not all platforms targeted by VGC are 64-bit anyway. It's probably not a big deal if VGC is slower on 32-bit platforms. Even in the future, 128-bit platforms are very unlikely to be used by VGC users any time soon (say, before 2050), if ever.

In addition, in graphics applications like VGC, using fixed-width integer types is often the appropriate choice anyway (communicating with the GPU, image file formats, etc.). Therefore, for the sake of consistency, it is probably a good choice to use these types for general purposes as well: it gives a highest chance of avoiding type-casts, and the added benefits of exact specifications is useful in some cases (bit masking, etc.). Not having to "guess" an allowed input range may prevent some bugs.

Unfortunately, fixed-width types are quite a pain to type and read (e.g., `int64_t`). This makes them less likely to be used in practice, despite often being the better choice. Therefore, I advocate for the following typedefs (similar to [Rust built-in types](https://doc.rust-lang.org/book/first-edition/primitive-types.html)):

- vgc::i8
- vgc::i16
- vgc::i32
- vgc::i64
- vgc::u8
- vgc::u16
- vgc::u32
- vgc::u64

Note that these would be defined directly in the "vgc" namespace, not in "vgc::core". This makes them directly accessible by any VGC library without the "core" prefix. Usually, even the most-used core functionality should be nested in the "core" namespace for consistency with Python bindings, but in this case these are types only to be used in C++, therefore the consistency argument applies less, and the added benefit of not typing "core::" seems well worth the exception.

As a sidenote, I would tend to advocate using i64 everywhere as the default (even for array sizes and indices), but this is another design decision, for now let's at least define the typedefs and try to use them more often.

**Comment by dalboris** [comment]
Related: interesting read on naming integer types in Rust:

http://featherweightmusings.blogspot.com/2014/10/thoughts-on-numeric-types.html

**Comment by dalboris** [comment]
I'm reopening this after thinking about it a little bit more. I'm currently in favor of defining a type `vgc::Int` which could be either `uint32_t` or `uint64_t`, controlled via a preprocessor macro switch. So basically, its semantics would be "signed integer of at least 32bit", similarly to how "long" is defined in the standard, except that we would stay in control of the exact type used, and we can later benchmark (e.g., in 2020) whether using 32bit vs 64bit really increases performance. If the performance gain is negligible in our targeted platforms (say, < 10% for most tasks), then we can change the documentation and guarantee that it is at least 64bit, and always make it a typedef for `uint64_t`. In fact, we may also decide to switch to a bignum implementation after more benchmarking, which would make its semantics closer to that of Python's `int`. I assume performance would suffer too much for this to be a good idea, but I'm curious to actually measure by how much, once the software is mature enough to be able to do a realistic benchmark on real-life data.

This `vgc::Int` type would be the preferred integer type for everything, from array sizes to indices to general data (window width/height, etc.). Note that values such as `width*height*depth*frames` could dangerously get close or be greater than the allowed range for 32-bit signed integers. Also, storing more than 4 billions elements, while uncommon, may actually be a use case we want to support. This is especially true in case of instancing: there might not *actually* be 4B+ elements stored, but the scene might still *represent* 4B+ elements, and we want to be able to represent this number in a consistent way with other integers used in the software. 

The shorter, familiar, and easily pronounceable name `Int` is likely to make the code more readable and increase adoption of the type. We could use longer names for the other integer types, e.g., `vgc::Uint64`, `vgc::Int32`, etc. Indeed, the really short `u64` or `i32` might not be necessary if `Int` is ubiquitous and the others rarely used.

**Comment by dalboris** [comment]
Somehow related: if we're using a library-defined `Int` type defined in a header `vgc/core/int.h` that we must include anyway, then we could define numeric limits directly in this header too, instead of of having them in `vgc/core/limits.h`. In fact, these limits are already defined as macros (evil!) in `<cstdint>` (see [here](https://en.cppreference.com/w/cpp/header/cstdint), so below seems like the most idiomatic way to do it:

```
// \file vgc/core/int.h

#include <cstdint>
#include <vgc/core/api.h>

namespace vgc 
{

using Int = std::int64_t;

inline constexpr Int maxInt() {
    return std::numeric_limits<int>::max();
}

} // namespace vgc
```

Maybe `maxInt` ought to be a namespaced constant rather than a constexpr function `maxInt()`, but this is far from clear. Should it have internal or external linkage? The former forces every compile unit to store the constant (waste memory), and the later prevents to optimize away things like "maxInt / 2". See [this](https://stackoverflow.com/questions/45710667/defining-global-constants-in-c1z/45712384#45712384) and [this](https://stackoverflow.com/questions/45710667/defining-global-constants-in-c1z/45712384#45712384), for example.

Other decision to make: is it better to have it in `<vgc/int.h>` or `<vgc/core/int.h>`?

**Comment by Robot-Fromage** [comment]
IMHO you should stick with the provided int64_t, int32_t for readability and avoid unnecessary headaches ;)
Since it is part of the standards, it could be better for readability too !

**Comment by dalboris** [comment]
Yes, as you can see from the posts above I've been thinking about it quite a lot. What you suggest is definitely a sensible option that I've considered, but since last month I've been thinking about it more and my current opinion is still to define `vgc::Int` as the preferred integer type to use.

In a nutshell, my conclusion is that built-in integer types in C++ are very low-level, and that it is the responsibility of any library or class to define a typedef for which integer type to use in which situation, and that built-in integer types shouldn't be used directly. In fact, this is what STL containers already do: `std::vector` defines `std::vector<T>::size_type`, and the recommended approach for portability is normally to use `std::vector<T>::size_type` instead of using `size_t` directly.

The equivalent for VGC is to define `vgc::Int`, and ask clients to use this type when handling VGC integers. This allows us to easily swap implementations for debug purposes, or depending on the platform. In a nutshell, it is more readable than `int64_t`, more flexible, and more future-proof, so I feel like it's the most correct and C++-idiomatic approach. And it has enormous value to be able to easily benchmark using 32-bit integers vs 64-bit integers later on.

**Comment by Robot-Fromage** [comment]
Using fixed-width integer types is really a good idea.
The readibility argument is debatable,  and STL containers do this for semantic reasons, what you propose is really just an alias that doesn't provide more information than the initial int64_t, it will rather hide some.
But it is true that your typedefs can provide some flexibility ;)
I guess i like it better when using the low level type directly to avoid confusion, but that's just me.

Your approach seems deeply thought anyway, i guess you have it sorted out !

**Comment by dalboris** [comment]
Somehow related, I came across this thread about the availability of various int types on different platforms, how Python used to handle it, and how it handles it now: 

https://bugs.python.org/issue17884
