### ISSUE TITLE
Python console doesn't support overwrite/insert mode

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#4]
Steps to reproduce: In the console, press the 'insert' key
Current behaviour: No effect.
Expected behaviour: It should toggle overwrite mode.

**Comment by myin142** [comment]
I added overwrite mode but I do not know if it is the desired result.

Should the cursor in overwrite mode always display a block, also at the end of a line?

**Comment by dalboris** [comment]
Nevermind, just tested a good old QPlainTexEdit and nothing happens when I press the "insert" key.

**Comment by dalboris** [comment]
Interestingly, the "Insert" key does nothing when I'm in a Chrome text edit either. But it does toggle overwrite mode on Sublime, Kate, and Qt Creator. You may want to look at Qt Creator source code for inspiration, see how they decided to handle that.

**Comment by myin142** [comment]
Do we need the feature, when we press 'tab' that all the previous 'spaces' will be converted to tabs? Qt Creator has this feature.

Overall these commits should enable overwrite mode. The one thing that is different than Qt Creator is  that the 'tab' can be smaller than a normal cursor block when it is inserted right before the next tab. It is not limited to overwrite mode only, but there you can clearly see the difference.

Should I just leave it like that?

**Comment by dalboris** [comment]
>Do we need the feature, when we press 'tab' that all the previous 'spaces' will be converted to tabs? Qt Creator has this feature.

No, we should definitely not convert spaces into tabs when we press 'tab'. If anything, we may want 'tab' to insert 4 spaces instead of one tab, since this is a Python console and PEP8 recommends 4-spaces per indentation level. But for now, let's keep the behaviour simple: a tab inserts a tab and a space insert a space. Future improvements include having à-la Qt Creator user preferences, but one thing at a time.

>The one thing that is different than Qt Creator is that the 'tab' can be smaller than a normal cursor block when it is inserted right before the next tab. It is not limited to overwrite mode only, but there you can clearly see the difference.

Just illustrating the problem for future reference:

I type:
```
aaaaaa<tab>something
aaaaaaaaa<tab>something
```
I see:
![gh4-01](https://user-images.githubusercontent.com/4809739/49889057-dc2b7e00-fe40-11e8-9f65-d61db92ecb00.png)

Is this what you're talking about? Indeed, Qt Creator does not have this issue because the width of one tab is fixed to be a multiple of the width of a space (instead of using tab-stops). Let's leave it like that for now, it's a very minor issue and people are not supposed to use tabs in the middle of a line anyway. Using leading tabs only do not cause any problems.

Alright, I looked at the commits. Overall it looks good, however, the following looks strange to me:
```
if ((cursorPosition < blockPosition + blockLength - 1) &&
    (document()->characterAt(cursorPosition) != QLatin1Char('\t')))
```
I get the following behaviour in overwrite mode:
![gh4-03](https://user-images.githubusercontent.com/4809739/49889963-231a7300-fe43-11e8-9a4c-5f3d0feb4287.gif)

But if I change the if condition to the simpler:
```
if (cursorPosition < blockPosition + blockLength - 1)
```
I get the following instead:
![gh4-02](https://user-images.githubusercontent.com/4809739/49890023-53faa800-fe43-11e8-9055-1ff7d040b3d4.gif)

I think the latter is the correct behaviour: the cursor shows you what will be replaced if you type a character. It makes sense to also "display the tab as if it were selected", since typing a character will replace the tab, as if we were not in overwrite mode and the tab was selected.

You can probably simplify the `else` case once doing this modification.

**Comment by myin142** [comment]
Ok, I have simplified it now and created a pull request.
