### ISSUE TITLE
Python console stops working after deleting last line.

### ISSUE THREAD

**Issue by myin142** [vgc/vgc#40]
Steps to reproduce:

- Inside python console press Ctrl+Enter
- Press Backspace

What happens:
Console is not taking any keyboard inputs anymore.

What should happen:
I assume that the line should not disappear.

But if code is edited like in #5  with a new line character inside, then it works again.

Example of not reacting console:
```
>>> for i in range(100):

``` 

After pasting "Copy/Paste Text with New Line at End":
```
>>> for i in Copy/Paste Text with New Line at End
>>> range(100):
```
It continues the next console line where the new line ended. And everything is now working again.

**Comment by dalboris** [comment]
Indeed, this one is quite a significant bug! Thanks for reporting and for the current workaround.
