### ISSUE TITLE
Slow Windows builds: vcpkg keeps re-compiling dependencies despite the use of cache.

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#700]
Not sure what's wrong with the caching mechanism, but we need to fix it.

**Comment by dalboris** [comment]
Alright, updating to a newer vcpkg commitId and to the latest runvcpkg action seems to have fixed the vcpkg caching issue. Still unclear on the root cause of the initial problem, but we previously had something like (building dependencies despite a cache hit):

```
Restore vcpkg and its artifacts from cache
  Cache key: 'runnerOS=win19-vcpkgGitCommit=8518284c18b9f47b1ccae804cb68694181b780a8_vcpkgJson=7396330cc4ce21619b016ca4b5900cf50195954497834e5cb17e70ede4384a2d'
  Cache restore keys: 'runnerOS=win19-vcpkgGitCommit=8518284c18b9f47b1ccae804cb68694181b780a8'
  Cached paths: 'D:/a/vgc/b/vcpkg_cache,D:\a\vgc\vgc\vcpkg,!D:\a\vgc\vgc\vcpkg\installed,!D:\a\vgc\vgc\vcpkg\vcpkg_installed,!D:\a\vgc\vgc\vcpkg\packages,!D:\a\vgc\vgc\vcpkg\buildtrees,!D:\a\vgc\vgc\vcpkg\downloads'
  Cache Size: ~299 MB (313447439 B)
  C:\Windows\System32\tar.exe -z -xf D:/a/_temp/da52f1f7-0630-41a6-a[24](https://github.com/vgc/vgc/runs/6427075243?check_suite_focus=true#step:10:24)5-571e80fd3b32/cache.tgz -P -C D:/a/vgc/vgc
  Cache hit, key = 'runnerOS=win19-vcpkgGitCommit=8518284c18b9f47b1ccae804cb68694181b780a8_vcpkgJson=7396330cc4ce21619b016ca4b5900cf50195954497834e5cb17e70ede4384a2d'

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#2
  * bzip2[core]:x64-windows -> 1.0.8#2
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.11.1
    harfbuzz[core]:x64-windows -> 3.2.0
  * libpng[core]:x64-windows -> 1.6.37#16
  * vcpkg-cmake[core]:x64-windows -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
  * vcpkg-tool-meson[core]:x64-windows -> 0.60.2#1
  * zlib[core]:x64-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from D:\a\vgc\b\vcpkg_cache in 786.5 us. Use --debug to see more details.
Starting package 1/9: zlib:x64-windows
Building package zlib[core]:x64-windows...

[...] // Many more lines building freetype, harfbuzz, and their dependencies  

Installing package harfbuzz[core]:x64-windows...
Elapsed time for package harfbuzz:x64-windows: 3.277 min

Total elapsed time: 4.798 min
```

And we now have this: (not building dependencies when there is a cache hit):

```
Restore vcpkg and its artifacts from cache
  Cache key: 'runnerOS=win1920220511.2-vcpkgGitCommit=14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44_vcpkgJson=7396330cc4ce21619b016ca4b5900cf50195954497834e5cb17e70ede4384a2d'
  Cache restore keys: 'runnerOS=win1920220511.2-vcpkgGitCommit=14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44'
  Cached paths: 'D:/a/vgc/b/vcpkg_cache,D:\a\vgc\vgc\vcpkg,!D:\a\vgc\vgc\vcpkg\installed,!D:\a\vgc\vgc\vcpkg\vcpkg_installed,!D:\a\vgc\vgc\vcpkg\packages,!D:\a\vgc\vgc\vcpkg\buildtrees,!D:\a\vgc\vgc\vcpkg\downloads'
  Cache Size: ~305 MB (319496250 B)
  C:\Windows\System[32](https://github.com/vgc/vgc/runs/6428453589?check_suite_focus=true#step:10:32)\tar.exe -z -xf D:/a/_temp/5a712fb1-f60b-4908-8403-3bebdcb6a910/cache.tgz -P -C D:/a/vgc/vgc
  Cache hit, key = 'runnerOS=win1920220511.2-vcpkgGitCommit=14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44_vcpkgJson=7396330cc4ce21619b016ca4b5900cf50195954497834e5cb17e70ede4384a2d'

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#2
  * bzip2[core]:x64-windows -> 1.0.8#2
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.11.1#1
    harfbuzz[core]:x64-windows -> 4.2.0
  * libpng[core]:x64-windows -> 1.6.37#17
  * vcpkg-cmake[core]:x64-windows -> 2022-05-06
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
  * vcpkg-tool-meson[core]:x64-windows -> 0.60.2#2
  * zlib[core]:x64-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Restored 9 packages from D:\a\vgc\b\vcpkg_cache in 889.3 ms. Use --debug to see more details.
Installing 1/9 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 7.428 ms
Installing 2/9 zlib:x64-windows...
Elapsed time to handle zlib:x64-windows: 11.87 ms
Installing 3/9 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 4.265 ms
Installing 4/9 libpng:x64-windows...
Elapsed time to handle libpng:x64-windows: 14.45 ms
Installing 5/9 bzip2:x64-windows...
Elapsed time to handle bzip2:x64-windows: 11.19 ms
Installing 6/9 brotli:x64-windows...
Elapsed time to handle brotli:x64-windows: 35.[74](https://github.com/vgc/vgc/runs/6428453589?check_suite_focus=true#step:12:74) ms
Installing 7/9 freetype:x64-windows...
Elapsed time to handle freetype:x64-windows: 40.27 ms
Installing 8/9 vcpkg-tool-meson:x64-windows...
Elapsed time to handle vcpkg-tool-meson:x64-windows: 267.8 ms
Installing 9/9 harfbuzz:x64-windows...
Elapsed time to handle harfbuzz:x64-windows: 133.7 ms

Total elapsed time: 12.53 s
```

This was the result for the commit in the pull request. In the merged commit, we got a cache miss, I suppose because GitHub uses a different cache for PR and normal runs. We'll see in the next merged PR if there is a cache hit and no building of vcpkg dependencies.

**Comment by dalboris** [comment]
Reopening this issue because vcpkg, *once again*, decided to rebuild everything despite having retrieving previously compiled dependencies from GitHub cache.

Example:

This build used the cache fine: https://github.com/vgc/vgc/actions/runs/3469759747/jobs/5797132607

![image](https://user-images.githubusercontent.com/4809739/202007864-54747c94-e3fa-4ca6-8f2f-46806a57202b.png)

But this build decided to recompile all dependencies: https://github.com/vgc/vgc/actions/runs/3473188383/jobs/5804926356

![image](https://user-images.githubusercontent.com/4809739/202008002-230878f5-542d-41e3-974f-5b50a4667c02.png)

Note that in both cases, the exact same vckpg folder is retrieved from GitHub cache. However, in the second build, vcpkg refused to use the binary cache present in the vcpkg folder, and create a new one. (See the line at the end of the screenshot "retrieved 9 packages" vs "retrieved 0 packages")

My understanding of why this problem occurs is that "binary caching in vcpkg" (see: https://vcpkg.io/en/docs/users/binarycaching.html) ignores previous cache entry when any of those do not match:

> Every file in the port directory
The triplet file and name
The C++ compiler executable
The C compiler executable
The set of features selected
Every dependency's package hash (note: this is that package's input hash, not contents)
All helper scripts referenced by portfile.cmake (heuristic)
The version of CMake used
The contents of any environment variables listed in VCPKG_ENV_PASSTHROUGH
The hash of the toolchain file (builtin or VCPKG_CHAINLOAD_TOOLCHAIN_FILE)

In our case, we can see that GitHub upgraded CMake in their hosted runners: the first build uses CMake 3.24.2, while the second build uses CMake 3.24.3. Therefore, vcpkg ignores our cached pre-compiled dependencies, and recompiles them. But because as far as "GitHub Cache" is concerned, we had a cache hit, so the newly compiled dependencies (with the more recent version of CMake) is not uploaded to the cache, so vcpkg will always recompile everything from now on.

Possible solutions are:
- Add the CMake version to the cache key, and possibly other versions that cause vcpkg to recompile when it doesn't match
- Disable binary caching

Unfortunately, the latter means that we need to "manually" specify the dependencies in the build script instead of simply giving the "vcpkg.json" file. Indeed, as far as I understand, it is impossible to disable binary caching when in "manifest mode" (the mode where vcpkg uses the vcpkg.json file). So if we disable binary caching, we also need to disable manifest mode, which is sad since we do provide a manifest file.

**Comment by Osyotr** [comment]
> Additionally, it was mentionned that it could be helpful, in the manifest file, to specify baselines 

It's not required if you only use builtin registry and pin vcpkg to a specific commit.

**Comment by dalboris** [comment]
@Osyotr Thanks, that makes sense.

**Comment by dalboris** [comment]
Reopening: vcpkg is again ignoring the cached binaries... so Windows builds are slow again.

https://github.com/vgc/vgc/actions/runs/3541034040/jobs/5944799272

![image](https://user-images.githubusercontent.com/4809739/203810161-dc0a99a6-77ad-4415-8b44-7e51ee28db8d.png)

**Comment by Osyotr** [comment]
Are you sure `D:\a\vgc\vgc\vcpkg\archives` has not been wiped by Github Actions?

**Comment by dalboris** [comment]
@Osyotr I haven't checked, but I see no reason why it would. Unfortunately I don't have time for further investigation right now, I will just disable manifest mode as I've lost too much time already on this, using manifest mode is clearly unreliable when the system keeps changing.
