### ISSUE TITLE
Improve Engine: multithreading, D3D11, more generic API

### ISSUE THREAD

**Issue by PixelRick** [vgc/vgc#789]
New features:
- multi-threading support
- thread-safe resource pointers
- state management to minimize the number of back-end graphics API calls.
- a Direct3D11 implementation
- getter/setter for most pipeline parameters common to most APIs (OpenGL, Metal, DirectX)
- removed window-resizing artifacts thanks to the D3D11 backend.

Yet to do:
- depth stencil state
- texture support in QglEngine
- better initialization
- test for nullptr in setters and define which state are allowed to be null.
- comments

**Comment by dalboris** [comment]
For newer improvements: #1201
