### ISSUE TITLE
Shift+Enter on Python Console creates line without prompt

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#8]
How to reproduce:
1. Type: `for i in range(42):`
2. Hit Shift+Enter
3. Type `    doSomething(i)`

What happens:
```
>>> for i in range(42):
        doSomething(i)
```

What should happen:
```
>>> for i in range(42):
...     doSomething(i)
```

**Comment by myin142** [comment]
Is it a good idea to just capture Shift+Enter input and remove the modifier like this:
```
else if ((e->text() == "\r") &&
         (e->modifiers() & Qt::SHIFT))
{
        e->setModifiers(Qt::NoModifier);
        QPlainTextEdit::keyPressEvent(e);
}
```

Because I think QPlainTextEdit treats Shift+Enter lines as one single line. Someone had a similar problem [here](http://www.jjoe64.com/2011/08/qplaintextedit-change-shiftreturn.html) He is also just removing the modifier.

**Comment by dalboris** [comment]
Yes, this seems like a good idea! Though, maybe it would be even better to "remove" the Shift modifier instead of setting `NoModifier`, and then should call `Console::keyPressEvent(e)` instead of `QPlainTextEdit::keyPressEvent(e)`. This would handle the case where users do Ctrl+Shift+Enter, and perhaps other more complicated scenarios.

Feel free to make the modifications, test if it works, add you copyright information to the COPYRIGHT file, and submit a pull request :) Of course, I can make the changes myself if you prefer.

**Comment by dalboris** [comment]
Note: the same problem was happening on macOS with other modifier keys. It is fixed as part as a fix of more general problems with the Enter key on macOS. See:
- #109
- https://github.com/vgc/vgc/commit/287bf20c16103edbf2bc1c7371e46972c6a8c360
