### ISSUE TITLE
Impossible to draw after using Ctrl+N 

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#847]
Steps to reproduce:

1. Open VGC Illustration
2. Draw some strokes
3. Ctrl+N
4. Draw some strokes

What should happens:

New strokes should be visible in step 4.

What happens:

The canvas stays blank after step 4. The only way to fix is to restart the app.

Note: the problem only occurs with Ctrl+N, not with File > New.

**Comment by PixelRick** [comment]
The issue is that Ctrl+N shortcut is disabled and N is a shortcut to a debug draw mode that doesn't draw curves.
Fix: Re-enable Ctrl+N. Rework canvas shortcuts (T: fill/wire; I: cycle tessellation levels; N, A, U, and F: removed shortcuts).
